server:
  port: 18081
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms
    username: root
    password: 123456
  redis:
    host: localhost
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /lf
    username: lf
    password: lf
    publisher-confirm-type: correlated
    publisher-returns: true
#  rabbitmq:
#    host: localhost
#    virtual-host: /lf
#    username: lf
#    password: lf
#    publisher-confirm-type: CORRELATED
#    publisher-returns: true
#    listener:
#      simple:
#        prefetch: 1
#        acknowledge-mode: manual
#        concurrency: 4
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
  global-config:
    db-config:
      id-type: auto


